# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "logging", "~> 2" # >= 2.0, <3

group :development do
  gem 'pry'
end
